theme = "onedark"

[keys.normal]
y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_before"

[editor]
mouse = false
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

