[[language]]
name = "markdown"
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }
auto-format = true

[[language]]
name = "yaml"
file-types = ["yaml", "yml"]
formatter = { command = "dprint", args = ["fmt", "--stdin", "yaml"] }
auto-format = true

[[language]]
name = "python"
formatter = { command = "dprint", args = ["fmt", "--stdin", "py"] }
auto-format = true

[language-server.terraform-ls]
command = "terraform-ls"
args = ["serve"]

[language-server.taplo]
config = {}
