version: "3"

vars:
  DOTFILES_DIR: "{{.HOME}}/.dotfiles"
  XDG_CONFIG_HOME: "{{.HOME}}/.config"
  XDG_DATA_HOME: "{{.HOME}}/.local/share"
  XDG_STATE_HOME: "{{.HOME}}/.local/state"
  XDG_CACHE_HOME: "{{.HOME}}/.cache"

tasks:
  default:
    desc: Show available tasks
    cmd: task -l

  bootstrap:
    desc: Complete setup - run all installation tasks
    cmds:
      - task: directories
      - task: oh-my-zsh
      - task: symlinks
      - task: brew
      - echo "Bootstrap complete! You may need to restart your shell."

  directories:
    desc: Create necessary directories (XDG, workspace, etc.)
    cmds:
      - mkdir -p ~/notes
      - mkdir -p ~/workspace
      - mkdir -p {{.XDG_CONFIG_HOME}}
      - mkdir -p {{.XDG_DATA_HOME}}
      - mkdir -p {{.XDG_STATE_HOME}}
      - mkdir -p {{.XDG_CACHE_HOME}}
      - mkdir -p {{.XDG_STATE_HOME}}/zsh
      - mkdir -p {{.XDG_CACHE_HOME}}/zsh
      - mkdir -p {{.XDG_DATA_HOME}}/terminfo
    status:
      - test -d ~/notes
      - test -d ~/workspace
      - test -d {{.XDG_CONFIG_HOME}}
      - test -d {{.XDG_DATA_HOME}}
      - test -d {{.XDG_STATE_HOME}}

  oh-my-zsh:
    desc: Install Oh-My-Zsh to XDG_DATA_HOME
    cmds:
      - sh -c "ZSH={{.XDG_DATA_HOME}}/.oh-my-zsh $(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended || true
    status:
      - test -d {{.XDG_DATA_HOME}}/.oh-my-zsh

  symlinks:
    desc: Create symlinks for all config files
    cmds:
      - task: link:zsh
      - task: link:git
      - task: link:helix
      - task: link:claude
      - task: link:starship
      - task: link:misc
      - task: link:private

  link:zsh:
    desc: Symlink zsh configuration
    cmds:
      - mkdir -p {{.XDG_CONFIG_HOME}}/zsh
      - ln -sf {{.DOTFILES_DIR}}/dotconfig/zsh/zshrc ~/.zshrc
      - ln -sf {{.DOTFILES_DIR}}/dotconfig/zsh/zshenv ~/.zshenv
      - ln -sf {{.DOTFILES_DIR}}/dotconfig/zsh/aliases.zsh {{.XDG_CONFIG_HOME}}/zsh/aliases.zsh
      - ln -sf {{.DOTFILES_DIR}}/dotconfig/zsh/exports.zsh {{.XDG_CONFIG_HOME}}/zsh/exports.zsh
      - ln -sf {{.DOTFILES_DIR}}/dotconfig/zsh/functions.zsh {{.XDG_CONFIG_HOME}}/zsh/functions.zsh
      - ln -sf {{.DOTFILES_DIR}}/dotconfig/zsh/completions.zsh {{.XDG_CONFIG_HOME}}/zsh/completions.zsh
      - ln -sf {{.DOTFILES_DIR}}/dotconfig/zsh/external.zsh {{.XDG_CONFIG_HOME}}/zsh/external.zsh

  link:git:
    desc: Symlink git configuration
    cmds:
      - ln -sf {{.DOTFILES_DIR}}/dotconfig/git/config {{.XDG_CONFIG_HOME}}/git/config
      - ln -sf {{.DOTFILES_DIR}}/dotconfig/git/ignore {{.XDG_CONFIG_HOME}}/git/ignore

  link:helix:
    desc: Symlink helix configuration
    cmds:
      - mkdir -p {{.XDG_CONFIG_HOME}}/helix
      - ln -sf {{.DOTFILES_DIR}}/dotconfig/helix/* {{.XDG_CONFIG_HOME}}/helix/

  link:claude:
    desc: Symlink Claude Code configuration
    cmds:
      - mkdir -p ~/.claude/agents
      - mkdir -p ~/.claude/commands
      - ln -sf {{.DOTFILES_DIR}}/dotconfig/claude/agents/* ~/.claude/agents/
      - ln -sf {{.DOTFILES_DIR}}/dotconfig/claude/commands/* ~/.claude/commands/
      - ln -sf {{.DOTFILES_DIR}}/dotconfig/claude/settings.json ~/.claude/settings.json

  link:starship:
    desc: Symlink starship configuration
    cmds:
      - ln -sf {{.DOTFILES_DIR}}/dotconfig/starship.toml {{.XDG_CONFIG_HOME}}/starship.toml

  link:misc:
    desc: Symlink miscellaneous config files
    cmds:
      - ln -sf {{.DOTFILES_DIR}}/dotconfig/dprint.json ~/.dprint.json
      - ln -sf {{.DOTFILES_DIR}}/dotconfig/editorconfig ~/.editorconfig

  link:private:
    desc: Symlink private files (not version controlled)
    cmds:
      - rm -rf ~/.private && ln -s {{.DOTFILES_DIR}}/.private ~/.private

  brew:
    desc: Install Homebrew packages from Brewfile
    dir: "{{.DOTFILES_DIR}}"
    cmds:
      - brew bundle --no-upgrade

  macos:
    desc: Apply macOS settings
    dir: "{{.DOTFILES_DIR}}"
    cmds:
      - bash macos/settings.sh

  unlink:
    desc: Remove all symlinks (use with caution)
    prompt: This will remove symlinks to dotfiles. Continue?
    cmds:
      - rm -f ~/.zshrc ~/.zshenv ~/.gitconfig ~/.gitignore_global ~/.dprint.json ~/.editorconfig
      - rm -f ~/.claude
      - rm -f {{.XDG_CONFIG_HOME}}/zsh/aliases.zsh
      - rm -f {{.XDG_CONFIG_HOME}}/zsh/exports.zsh
      - rm -f {{.XDG_CONFIG_HOME}}/zsh/functions.zsh
      - rm -f {{.XDG_CONFIG_HOME}}/zsh/completions.zsh
      - rm -f {{.XDG_CONFIG_HOME}}/zsh/external.zsh
      - rm -f {{.XDG_CONFIG_HOME}}/helix
      - rm -f {{.XDG_CONFIG_HOME}}/starship.toml
      - rm -rf ~/.private
      - echo "Symlinks removed"

  check:
    desc: Check which symlinks are properly configured
    silent: true
    cmds:
      - |
          echo "Checking dotfiles symlinks..."
          echo ""

          echo "=== ZSH Configuration ==="
          ls -la ~/.zshrc ~/.zshenv 2>/dev/null || echo "⚠️  ZSH rc/env files missing"
          ls -la {{.XDG_CONFIG_HOME}}/zsh/aliases.zsh 2>/dev/null || echo "⚠️  aliases.zsh missing"
          ls -la {{.XDG_CONFIG_HOME}}/zsh/exports.zsh 2>/dev/null || echo "⚠️  exports.zsh missing"
          ls -la {{.XDG_CONFIG_HOME}}/zsh/functions.zsh 2>/dev/null || echo "⚠️  functions.zsh missing"
          ls -la {{.XDG_CONFIG_HOME}}/zsh/completions.zsh 2>/dev/null || echo "⚠️  completions.zsh missing"
          ls -la {{.XDG_CONFIG_HOME}}/zsh/external.zsh 2>/dev/null || echo "⚠️  external.zsh missing"
          echo ""

          echo "=== Git Configuration ==="
          ls -la {{.XDG_CONFIG_HOME}}/git/config 2>/dev/null || echo "⚠️  git config missing"
          ls -la {{.XDG_CONFIG_HOME}}/git/ignore 2>/dev/null || echo "⚠️  git ignore missing"
          echo ""

          echo "=== Helix Editor ==="
          ls -la {{.XDG_CONFIG_HOME}}/helix 2>/dev/null || echo "⚠️  Helix config missing"
          echo ""

          echo "=== Claude Code ==="
          ls -la ~/.claude/agents/ 2>/dev/null | grep -v '^total' | tail -n +2 || echo "⚠️  Claude agents symlinks missing"
          ls -la ~/.claude/commands/ 2>/dev/null | grep -v '^total' | tail -n +2 || echo "⚠️  Claude commands symlinks missing"
          ls -la ~/.claude/settings.json 2>/dev/null || echo "⚠️  Claude settings.json missing"
          echo ""

          echo "=== Starship Prompt ==="
          ls -la {{.XDG_CONFIG_HOME}}/starship.toml 2>/dev/null || echo "⚠️  Starship config missing"
          echo ""

          echo "=== Miscellaneous ==="
          ls -la ~/.dprint.json 2>/dev/null || echo "⚠️  dprint.json missing"
          ls -la ~/.editorconfig 2>/dev/null || echo "⚠️  editorconfig missing"
          ls -ld ~/.private 2>/dev/null || echo "⚠️  private directory missing"
          echo ""

          echo "=== Oh-My-Zsh Installation ==="
          ls -ld {{.XDG_DATA_HOME}}/.oh-my-zsh 2>/dev/null || echo "⚠️  Oh-My-Zsh not installed"
