version: "3"

vars:
  DOTFILES_DIR: "{{.HOME}}/.dotfiles"
  XDG_CONFIG_HOME: "{{.HOME}}/.config"
  XDG_DATA_HOME: "{{.HOME}}/.local/share"
  XDG_STATE_HOME: "{{.HOME}}/.local/state"
  XDG_CACHE_HOME: "{{.HOME}}/.cache"

tasks:
  default:
    desc: Show available tasks
    cmd: task -l

  bootstrap:
    desc: Complete setup - run all installation tasks
    cmds:
      - task: directories
      - task: oh-my-zsh
      - task: symlinks
      - task: brew
      - echo "Bootstrap complete! You may need to restart your shell."

  directories:
    desc: Create necessary directories (XDG, workspace, etc.)
    cmds:
      - mkdir -p ~/notes
      - mkdir -p ~/workspace
      - mkdir -p {{.XDG_CONFIG_HOME}}
      - mkdir -p {{.XDG_DATA_HOME}}
      - mkdir -p {{.XDG_STATE_HOME}}
      - mkdir -p {{.XDG_CACHE_HOME}}
      - mkdir -p {{.XDG_STATE_HOME}}/zsh
      - mkdir -p {{.XDG_CACHE_HOME}}/zsh
      - mkdir -p {{.XDG_DATA_HOME}}/terminfo
    status:
      - test -d ~/notes
      - test -d ~/workspace
      - test -d {{.XDG_CONFIG_HOME}}
      - test -d {{.XDG_DATA_HOME}}
      - test -d {{.XDG_STATE_HOME}}

  oh-my-zsh:
    desc: Install Oh-My-Zsh to XDG_DATA_HOME
    cmds:
      - sh -c "ZSH={{.XDG_DATA_HOME}}/.oh-my-zsh $(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended || true
    status:
      - test -d {{.XDG_DATA_HOME}}/.oh-my-zsh

  symlinks:
    desc: Create symlinks for all config files
    cmds:
      - task: link:zsh
      - task: link:git
      - task: link:nvim
      - task: link:claude
      - task: link:mise
      - task: link:starship
      - task: link:misc
      - task: link:aerospace
      - task: link:ghostty
      - task: link:tmux
      - task: link:private

  link:zsh:
    desc: Symlink zsh configuration
    vars:
      ZSH_CONFIGS: aliases.zsh exports.zsh functions.zsh completions.zsh external.zsh todos.zsh
    cmds:
      - mkdir -p {{.XDG_CONFIG_HOME}}/zsh
      - ln -sf {{.DOTFILES_DIR}}/dotconfig/zsh/zshrc ~/.zshrc
      - ln -sf {{.DOTFILES_DIR}}/dotconfig/zsh/zshenv ~/.zshenv
      - for: { var: ZSH_CONFIGS }
        cmd: ln -sf {{.DOTFILES_DIR}}/dotconfig/zsh/{{.ITEM}} {{.XDG_CONFIG_HOME}}/zsh/{{.ITEM}}

  link:git:
    desc: Symlink git configuration
    cmds:
      - mkdir -p {{.XDG_CONFIG_HOME}}/git
      - ln -sf {{.DOTFILES_DIR}}/dotconfig/git/config {{.XDG_CONFIG_HOME}}/git/config
      - ln -sf {{.DOTFILES_DIR}}/dotconfig/git/ignore {{.XDG_CONFIG_HOME}}/git/ignore

  link:nvim:
    desc: Symlink neovim configuration
    cmds:
      - mkdir -p {{.XDG_CONFIG_HOME}}/nvim/lua
      - ln -sf {{.DOTFILES_DIR}}/dotconfig/nvim/init.lua {{.XDG_CONFIG_HOME}}/nvim/init.lua
      - ln -sf {{.DOTFILES_DIR}}/dotconfig/nvim/lua/plugins {{.XDG_CONFIG_HOME}}/nvim/lua/plugins

  link:claude:
    desc: Symlink Claude Code configuration
    cmds:
      - mkdir -p ~/.claude
      - ln -sfn {{.DOTFILES_DIR}}/dotconfig/claude/skills ~/.claude/skills
      - ln -sf {{.DOTFILES_DIR}}/dotconfig/claude/settings.json ~/.claude/settings.json
      - ln -sf {{.DOTFILES_DIR}}/dotconfig/claude/CLAUDE.md ~/.claude/CLAUDE.md

  link:starship:
    desc: Symlink starship configuration
    cmds:
      - ln -sf {{.DOTFILES_DIR}}/dotconfig/starship.toml {{.XDG_CONFIG_HOME}}/starship.toml

  link:mise:
    desc: Symlink mise configuration
    cmds:
      - mkdir -p {{.XDG_CONFIG_HOME}}/mise
      - ln -sf {{.DOTFILES_DIR}}/dotconfig/mise/config.toml {{.XDG_CONFIG_HOME}}/mise/config.toml

  link:misc:
    desc: Symlink miscellaneous config files
    cmds:
      - ln -sf {{.DOTFILES_DIR}}/dotconfig/dprint.json ~/.dprint.json
      - ln -sf {{.DOTFILES_DIR}}/dotconfig/editorconfig ~/.editorconfig

  link:aerospace:
    desc: Symlink aerospace configuration
    cmds:
      - mkdir -p {{.XDG_CONFIG_HOME}}/aerospace
      - ln -sf {{.DOTFILES_DIR}}/dotconfig/aerospace/aerospace.toml {{.XDG_CONFIG_HOME}}/aerospace/aerospace.toml

  link:ghostty:
    desc: Symlink Ghostty terminal configuration
    cmds:
      - mkdir -p {{.XDG_CONFIG_HOME}}/ghostty
      - ln -sf {{.DOTFILES_DIR}}/dotconfig/ghostty/config {{.XDG_CONFIG_HOME}}/ghostty/config

  link:tmux:
    desc: Symlink tmux configuration
    cmds:
      - mkdir -p {{.XDG_CONFIG_HOME}}/tmux
      - ln -sf {{.DOTFILES_DIR}}/dotconfig/tmux/tmux.conf {{.XDG_CONFIG_HOME}}/tmux/tmux.conf

  link:private:
    desc: Symlink private files (not version controlled)
    cmds:
      - rm -rf ~/.private && ln -s {{.DOTFILES_DIR}}/.private ~/.private

  brew:
    desc: Install Homebrew packages from Brewfile
    dir: "{{.DOTFILES_DIR}}"
    cmds:
      - brew bundle --no-upgrade

  macos:
    desc: Apply macOS settings
    dir: "{{.DOTFILES_DIR}}"
    cmds:
      - bash macos/settings.sh

  unlink:
    desc: Remove all symlinks (use with caution)
    prompt: This will remove symlinks to dotfiles. Continue?
    cmds:
      - rm -f ~/.zshrc ~/.zshenv ~/.dprint.json ~/.editorconfig
      - rm -rf ~/.claude/skills ~/.claude/settings.json ~/.claude/CLAUDE.md
      - rm -rf {{.XDG_CONFIG_HOME}}/zsh
      - rm -rf {{.XDG_CONFIG_HOME}}/git
      - rm -rf {{.XDG_CONFIG_HOME}}/nvim
      - rm -rf {{.XDG_CONFIG_HOME}}/mise
      - rm -rf {{.XDG_CONFIG_HOME}}/aerospace
      - rm -rf {{.XDG_CONFIG_HOME}}/ghostty
      - rm -rf {{.XDG_CONFIG_HOME}}/tmux
      - rm -f {{.XDG_CONFIG_HOME}}/starship.toml
      - rm -rf ~/.private
      - echo "Symlinks removed"

  # === Personal Management System ===
  notes:init:
    desc: Initialize personal management directory under ~/notes
    cmds:
      - mkdir -p ~/notes/pm-system
      - mkdir -p ~/notes/pm-system/planning
      - mkdir -p ~/notes/pm-system/planning/quarters
      - mkdir -p ~/notes/pm-system/planning/months
      - mkdir -p ~/notes/pm-system/planning/weeks
    status:
      - test -d ~/notes/pm-system
      - test -d ~/notes/pm-system/planning
      - test -d ~/notes/pm-system/planning/quarters
      - test -d ~/notes/pm-system/planning/months
      - test -d ~/notes/pm-system/planning/weeks

  check:
    desc: Check which symlinks are properly configured
    silent: true
    vars:
      SYMLINKS: >-
        ~/.zshrc
        ~/.zshenv
        {{.XDG_CONFIG_HOME}}/zsh/aliases.zsh
        {{.XDG_CONFIG_HOME}}/zsh/exports.zsh
        {{.XDG_CONFIG_HOME}}/zsh/functions.zsh
        {{.XDG_CONFIG_HOME}}/zsh/completions.zsh
        {{.XDG_CONFIG_HOME}}/zsh/external.zsh
        {{.XDG_CONFIG_HOME}}/zsh/todos.zsh
        {{.XDG_CONFIG_HOME}}/git/config
        {{.XDG_CONFIG_HOME}}/git/ignore
        {{.XDG_CONFIG_HOME}}/nvim/init.lua
        ~/.claude/skills
        ~/.claude/settings.json
        ~/.claude/CLAUDE.md
        {{.XDG_CONFIG_HOME}}/mise/config.toml
        {{.XDG_CONFIG_HOME}}/aerospace/aerospace.toml
        {{.XDG_CONFIG_HOME}}/ghostty/config
        {{.XDG_CONFIG_HOME}}/tmux/tmux.conf
        {{.XDG_CONFIG_HOME}}/starship.toml
        ~/.dprint.json
        ~/.editorconfig
        ~/.private
        {{.XDG_DATA_HOME}}/.oh-my-zsh
    cmds:
      - echo "Checking dotfiles symlinks..."
      - for: { var: SYMLINKS }
        cmd: ls -la {{.ITEM}} 2>/dev/null || echo "⚠️  {{.ITEM}} missing"
