[general]
live_config_reload = true

[window]
option_as_alt = "Both"
decorations = "none"
dynamic_padding = false
padding = { x = 6, y = 6 }

[font]
size = 15.0
normal = { family = "Dank Mono" }
bold = { family = "Dank Mono" }
italic = { family = "Dank Mono" }
bold_italic = { family = "Dank Mono" }
glyph_offset = { x = 0, y = 1 }
offset = { x = 0, y = 1 }

[colors]
draw_bold_text_with_bright_colors = true

[selection]
save_to_clipboard = true
semantic_escape_chars = ",`|:\"' ()[]{}<>"

[cursor]
style = { shape = "Beam" }

[[keyboard.bindings]]
key = "Comma"
mods = "Command"

[keyboard.bindings.command]
args = ["-c", "open $DOTFILES/.alacritty.toml"]
program = "sh"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = " "
key = "Space"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"
