# Enable profiling for debugging startup time (uncomment when needed)
# zmodload zsh/zprof

# Performance optimsations
DISABLE_AUTO_UPDATE="true"
DISABLE_MAGIC_FUNCTION="true"
DISABLE_COMPFIX="true"
skip_global_compinit=1

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set completion dump location
export ZSH_COMPDUMP="$HOME/.zcompdump"

# Optimized completion loading - cache compinit for 24 hours
# Based on: https://gist.github.com/ctechols/ca1035271ad134841284
autoload -Uz compinit
for dump in ~/.zcompdump(N.mh+24); do
  compinit -d "$ZSH_COMPDUMP"
  break
done
compinit -C -d "$ZSH_COMPDUMP"

# Theme is set via `zplug`, see `config/zplugrc`.
# ZSH_THEME="spaceship"

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE='false'

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE='false'

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="false"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS='yyyy-mm-dd'

# Commands starting from " " (whitespace) won't be saved in history:
HIST_IGNORE_SPACE='true'

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
# plugins=()

# Sourcing the Oh-My-ZSH source:
source "$ZSH/oh-my-zsh.sh"

# This PATH needs to be set before all other modifications:
export PATH='/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'


# === Plugin management ===

# zgen - fast plugin manager with static script generation
source ~/.zgen/zgen.zsh

# Check if zgen needs to regenerate its init script
if ! zgen saved; then
  echo "Creating a zgen save..."

  # Load plugins (equivalent to previous zplug setup)
  zgen load Aloxaf/fzf-tab
  zgen load zsh-users/zsh-syntax-highlighting
  zgen load MichaelAquilina/zsh-you-should-use
  zgen load spaceship-prompt/spaceship-prompt spaceship

  # Generate the init script from plugins above
  zgen save
fi


# === Shell parts ===

source "$HOME/.shell/.exports"
source "$HOME/.shell/.aliases"
source "$HOME/.shell/.external"
source "$HOME/.shell/.completions"

# Load command functions
if [[ -d "$HOME/.shell/commands" ]]; then
  for cmd_file in "$HOME/.shell/commands"/*; do
    [[ -f "$cmd_file" ]] && source "$cmd_file"
  done
fi


# === Local variables and overrides ===

if [[ -f "$HOME/.shell_env_local" ]]; then
  source "$HOME/.shell_env_local"
fi



# Generated for envman. Do not edit.
[ -s "$HOME/.config/envman/load.sh" ] && source "$HOME/.config/envman/load.sh"

# Print profiling results at the end (uncomment when needed)
# zprof
